### PR TITLE
Add go.mod

### PR DESCRIPTION
**Pull request by ntrrg**
Hello, this fixes errors for Go modules users

### CODE REVIEW

**Comment by prochac** [comment]
https://github.com/blevesearch/bleve/issues/1147

**Comment by bikbah** [comment]
@mschoch Hello! It would be great to review and merge this PR, in order to start using go modules. Any reasons for not doing this?

**Comment by mschoch** [comment]
Hello @bikbah,  

We have an independent effort to adopt Go modules in-progress.  The reason it's somewhat more complicated is that Bleve has both a long history, and new improvements we can't ship without proper versioning.  This plan included a v2, and Go modules with v2 has some additional challenges.

The crucial problem we are solving is the ability for a single build of bleve to read/write more than one file format (necessary before we can introduce a breaking change).  The good news is that we are in the late stages of testing this now, and hope to communicate details to the community very soon.

**Comment by mschoch** [comment]
Closing this as bleve now has a go.mod.

**Pull request closed without merging**
