### PR TITLE
Fix spelling and typo mistakes

### PR DESCRIPTION
**Pull request by bengadbois**
This should only be code and documentation fixes - not test data with intentional misspellings.

### CODE REVIEW

**Comment by bengadbois** [comment]
I wasn't interested in `review and sign the Contributor Agreement and send a scanned image to info@Couchbase.com, or send an original by regular mail to Couchbase` from the [CLA](https://github.com/blevesearch/bleve/blob/master/CONTRIBUTING.md)

**Comment by mschoch** [comment]
There is an electronic option as well, or were you not agreeable?

**Comment by bengadbois** [comment]
Ah, I missed that, was just going off the top of CLA. I have now logged in (which I think counts as signing?).

I don't seem have to permissions to repoen this PR, but I'm okay doing so and merging it.

**Comment by mschoch** [comment]
Can you navigate to this page, and follow the instructions? (should be pushing a button I think)

http://review.couchbase.org/#/settings/new-agreement

**Comment by bengadbois** [comment]
Okay, done!

**Comment by mschoch** [comment]
Thanks, I see now that you've signed it.  Unfortunately, it won't let me reopen the PR either because it says the branch was deleted.  Do you still have the changes that you can push again?

**Comment by bengadbois** [comment]
It doesn't seem happy, so I've opened a new PR

**Pull request closed without merging**
