### PR TITLE
minor memory savings during collection

### PR DESCRIPTION
**Pull request by sreekanth-cb**

### CODE REVIEW

**Comment by mschoch** [comment]
can you elaborate how this saves memory?  does it have to do with the closure creating garbage inside a hot loop?

**Comment by sreekanth-cb** [comment]
yes, thats the thinking..

**Comment by mschoch** [comment]
thinking or measurement? seems like this one should be straightforward to verify with bleve-bench

**Comment by mschoch** [comment]
@sreekanth-cb I believe this has already been rolled into one of the other PRs and merged.

**Comment by sreekanth-cb** [comment]
thats right @mschoch , thx!

**Pull request closed without merging**
