### PR TITLE
add goleveldb as an experimental alternative KV Store

### PR DESCRIPTION
**Pull request by indraniel**
This pull request introduces [goleveldb][1] as an experimental KV store alternative.  It is based from a  discussion on a [bleve google groups thread][2].  

I think I've performed the instructions mentioned on the [contributing section of the wiki][3].  Let me know if there are any issues I should address.

[1]: https://github.com/syndtr/goleveldb
[2]: https://groups.google.com/forum/#!topic/bleve/aHZ8gmihLiY
[3]: https://github.com/blevesearch/bleve/wiki/Contributing

### CODE REVIEW

**Comment by indraniel** [comment]
Looks like I'm failing the `errcheck ./...` command on [TravisCI][1].  I'm not clear on what these error signify.  

[1]: https://travis-ci.org/blevesearch/bleve/builds/57988015#L792

**Comment by mschoch** [comment]
Its OK, I recently added that check, so I'll taken on the effort of fixing it up.  I'm just pulling the code over to start the process now.

**Comment by mschoch** [comment]
Also, FYI errcheck is a pretty useful too.  I learned about it while at GopherCon India.  The tool will review the specified packages and look for functions that return an error that you're ignoring.  Many of the cases, are ones where it seems like no big deal, but I can honestly say that while going through and fixing them in the entire codebase I found 3 or 4 very subtle bugs.

**Comment by indraniel** [comment]
Neat!  This is the first I've heard about errcheck.  

I wonder why the similar `index/store/leveldb` code directory doesn't have the same issue too?  I used the original leveldb sub-directory as a template for the goleveldb sub-directory.

**Comment by indraniel** [comment]
Ah.  I see you've [recently updated][1] the corresponding leveldb code like:

```Go
defer s.Close()
```

to: 

```Go
defer func() {
    err := s.Close()
    if err != nil {
        t.Fatal(err)
    }
}()
```

[1]: https://github.com/blevesearch/bleve/issues/169

**Pull request merged**
