### PR TITLE
adds examples for most query functions

### PR DESCRIPTION
**Pull request by sacheendra**
This has examples for most functions required while building a query. Related to #79

### CODE REVIEW

**Comment by sacheendra** [comment]
This is related to #79

**Comment by mschoch** [comment]
Thanks for this.  I'd like to merge this, there are 2 things.

1.  I think its important for the examples to not ignore the returned error value.  I know it makes the examples a bit more verbose, but ignoring helpful error messages has been a frequent source of confusion for new bleve users.  I think the examples should store the error result into a variable, and assert that it is nil.

2.  Can you submit the Couchbase CLA?  There are instructions here: https://github.com/blevesearch/bleve/wiki/Contributing

Thanks.

**Comment by sacheendra** [comment]
assertion of errors has been added.
I did submit the Couchbase SLA.

**Comment by mschoch** [comment]
Thanks for the contribution!

**Pull request merged**
