### PR TITLE
MB-37962 - graceful handling of the json encode errors

### PR DESCRIPTION
**Pull request by sreekanth-cb**
Handle the json encode errors than panicing
in the response encoder.

### CODE REVIEW

**Comment by mschoch** [comment]
At a minimum we need to change the method name as well.  In Go, the prefix "must" is a convention used for methods that either succeed or panic.

This code is so old, I don't remember why we ever did it this way instead of returning an error and letting the caller decide what to do.

**Comment by sreekanth-cb** [comment]
Is there a name you prefer @mschoch , just encode or encodeResponse ?

**Comment by mschoch** [comment]
Looking closer, I'm now -1 on this change.  By the time we've encountered the error, we may have already started writing the response.  If we then call `showError` we may attempt to set a header again which is invalid.  Exactly how it fails at that point is unclear, since nothing on this path returns error.

Do you have a bug where this actually happens?

**Comment by sreekanth-cb** [comment]
Yes, the MB is put in the PR title - https://issues.couchbase.com/browse/MB-37962

thats right, then one option would be to switch to json.Marshal beforehand for detecting any marshal errors and set the headers accordingly () ?  

Not sure whether the lack of the streamed write capabilities is such a big concern though here?

**Comment by mschoch** [comment]
The error is coming from the I/O (timeout), so I don't think marshaling first would have helped.

**Comment by sreekanth-cb** [comment]
yikes... thats true..

**Comment by mschoch** [comment]
This is actually a good example of why the `bleve/http` package should not exist.

The HTTP handler API is such that we cannot return the error for the caller to decide what to do.  Our choices are to panic (undesirable because the entire process exits), log it (something bleve generally doesn't do), or do nothing.  Writing the error the response in not possible for cases like this, where the error is our inability to write the response.

**Comment by sreekanth-cb** [comment]
Shall we use HTTP Trailer headers here? but that will be unconventional too..

I just wanted a better handling of errors here than panicking.. 
The issue in CB is a bigger one and that mostly has to do with the way the system/node is overloaded I guess.. The fix for it would be a broader one with more resource pruning/judicious usage across the stack.

**Comment by mschoch** [comment]
The issue is that we cannot write successfully to the socket, so it doesn't matter whether we call it header/body/trailer-header.  As I said before, the choices I see are:
- panic (what we do today)
- log (not possible today without further changes, only top-level bleve pkg has access to a configured logger)
- do nothing
- add yet another callback to let the user choose between the first 3 options (dislike this because I would prefer we remove this package instead)

I don't see any other choices, do you?

**Comment by sreekanth-cb** [comment]
Strangely, this package has it's own logger. 
https://github.com/blevesearch/bleve/blob/9b6e89951d4e9207356a833a7d99577cfe249208/http/util.go#L45

Now, I am thinking between "do nothing Vs Panic", and finding it difficult to decide.. 
Perhaps eventually has to choose the "do nothing" option..

**Comment by mschoch** [comment]
@sreekanth-cb my honest opinion is that these handlers should move into FTS, then you can do proper logging, and not panic.  Do you see any problem with that?

**Comment by mschoch** [comment]
Oh, another idea, since the assertion is kind of weak.  You could have an actual "unit test" in the mapping package that just tests the `defaultAnalyzerName` function.  That might be cleaner?

**Comment by mschoch** [comment]
Sorry @sreekanth-cb I posted some comments I intended for a PR by @abhinavdangeti

**Comment by sreekanth-cb** [comment]
Closing this PR as this needs to be handled at the app level.

**Pull request closed without merging**
