### PR TITLE
add phrase_prefix_query

### PR DESCRIPTION
**Pull request by ansjsun**

### CODE REVIEW

**Comment by fi0** [comment]
Hi, why is this closed?

**Comment by ansjsun** [comment]
It's been too long. I don't think they need it

**Comment by khayyamsaleem** [comment]
I think there still isn't anything that implements this functionality in the core. Can this PR be re-opened?

**Comment by khayyamsaleem** [comment]
@mschoch would significant work be required to catch this PR up with the latest changes to the repo? If necessary, I can try picking it up.

**Pull request closed without merging**
