### PR TITLE
Added Russian analyzer with snowball stemmer

### PR DESCRIPTION
**Pull request by sokolovstas**
New implementation of #538

### CODE REVIEW

**Comment by sokolovstas** [comment]
Close to rerun travis

**Comment by sokolovstas** [comment]
Checked by Travis

**Comment by egorsmkv** [comment]
Any news about merging?

**Comment by mschoch** [comment]
Yes, sorry for the long delay, I wanted to produce these for all the languages in blevex, but I got delayed.  I will merge this one later today.  I will start with your PR and make a few minor changes in another commit stacked on it.  I'm going to remove the snowball stemmer that isn't used, and I'll probably use the same stop word list as the one in blevex (https://github.com/blevesearch/blevex/blob/master/lang/ru/stop_words_ru.go).

**Comment by mschoch** [comment]
Actually, one more thing.  In order for me to use your commit as  starting point I need you to sign the Couchbase CLA.  See https://github.com/blevesearch/bleve/blob/master/CONTRIBUTING.md

**Comment by sokolovstas** [comment]
@mschoch I think I have signed some time ago. Signed now one more time.

**Comment by mschoch** [comment]
@egorsmkv sorry I'm having trouble finding your record in our system.  Can you provide me your email address for verification?  If you want to keep it private you can email it to me at marty.schoch@gmail.com

**Comment by sokolovstas** [comment]
@mschoch this is my pull request :)

Username | sokolovstas
Full Name | Stanislav
Email Address | sokolov.stas@gmail.com
Registered | Jan 10, 2018 8:22 PM
Account ID | 1004249

**Comment by mschoch** [comment]
I'm still not finding it.  The instructions aren't very clear.  After signing in, can you click on "Settings" on the menu under your username in the upper-right corner.  Then under settings select "Agreements", and finally press "New Contributor Agreement".

**Comment by sokolovstas** [comment]
Done!

**Comment by mschoch** [comment]
I've got it now. Thanks.

**Comment by egorsmkv** [comment]
Cool. Thanks!

**Pull request merged**
