### PR TITLE
Initial commit for examples of using Bleve

### PR DESCRIPTION
**Pull request by oskarwojciski**
Related to #1031

### CODE REVIEW

**Comment by mschoch** [comment]
Seems like there is some overlap with the existing examples.  https://github.com/blevesearch/bleve/blob/master/examples_test.go

**Comment by oskarwojciski** [comment]
> Seems like there is some overlap with the existing examples. https://github.com/blevesearch/bleve/blob/master/examples_test.go

you're right but I like to have things more structured so maybe unify to one version?

**Comment by hubyhuby** [comment]
@oskarwojciski ,
This is wonderfull to have those examples now. Thanks.
An interesting one would be Geo localised search ;which doesn t seem to be in your PR.

**Comment by paivagustavo** [comment]
I'm just trying out Bleve and I have to say that this type of examples are more effective for me.

Sure `examples_test.go` have some overlapping but having a more structured and friendly examples helps for newcomers like myself as I find that the [documentation](http://blevesearch.com/docs/Home/) seems to be a lot more for terminology than a documentation.

I think that these type of examples should be extended and the documentation be improved, with some examples of types of indexing mapping and so on. As I said, I only discovered bleve today, so take this with a little grain of salt. And thanks @oskarwojciski  for this examples it helped me.

**Pull request closed without merging**
