### PR TITLE
Deploy errcheck on go1.11

### PR DESCRIPTION
**Pull request by abhinavdangeti**

### CODE REVIEW

**Comment by abhinavdangeti** [comment]
Hey @mschoch, still trying to figure out the reason for the recent go list failures versions prior to 1.11. I'll open this (or a better change) up for review, once I have a handle on it.

**Comment by mschoch** [comment]
Cool, ya I figured it was related to that.  I was just hoping you already found the answer :)

**Comment by steveyen** [comment]
Thanks @abhinavdangeti 

Yah, I too am not sure why errcheck recently went funky on go 1.9 & 1.10.

+2, imho, as even if we don't know why errcheck (go list?) went weird, we still have errcheck happening for go 1.11 and imho getting rid of the low-signal noise in travis-CI for those go versions < 1.11 is fine by me

**Comment by mschoch** [comment]
Alright, as a compromise, create another issue logging that we disabled errcheck in some environments.  That way we won't completely forget.  Either we fix it, or eventually the older Go versions fall off the supported cliff.

If we do that I'm OK to merge.

**Comment by abhinavdangeti** [comment]
@mschoch created an issue ticket to track this.

**Pull request merged**
