### PR TITLE
WIP: Switch to use bbolt

### LINKED ISSUE #783: Replace boltdb with bbolt
Since _boltdb_ is no longer actively maintained, it seems proper to replace it with [**bbolt**](https://github.com/coreos/bbolt), a _boltdb_ fork maintained by _coreos_.

### PR DESCRIPTION
**Pull request by techknowlogick**
Fix #783

### CODE REVIEW

**Comment by networkimprov** [comment]
Pls use github.com/etcd-io/bbolt, not go.etcd.io

**Comment by techknowlogick** [comment]
@networkimprov ok. just pushed an update.

**Comment by cristaloleg** [comment]
Kindly ping 😉

**Comment by techknowlogick** [comment]
@cristaloleg assuming you are giving a ping because of my message in the issue re: me not be available till new year to look at this and you want to take over PR, and as such I've giving you commit access to my fork.

If my above assumption is incorrect, please ignore the invite to the repo 😄

**Comment by mschoch** [comment]
We fixed this and merged it here: #1134

**Comment by techknowlogick** [comment]
@mschoch that’s fantastic! Thanks for taking over this PR, and completing it.

**Pull request closed without merging**
