### PR TITLE
Improve docs -Update README.md

### PR DESCRIPTION
**Pull request by sahil431**

### CODE REVIEW

**Review by mschoch — COMMENTED** [review]
This does not improve docs, it is spam.  Your account will be reported.

**Comment by sahil431** [comment]
Sorry for  all the trouble,
I am a new user , hope you understand.

**Comment by mschoch** [comment]
I'm willing to consider that I was wrong.  Please explain how you feel this change improves the documentation.

**Comment by mschoch** [comment]
Before your proposed change:

before

After your proposed change:

after

**Comment by sahil431** [comment]
Sir
First of all I m a 4th class student
I want to learn and improve my Skills in programming language. I
accidentally open this page. I don't know how to close this so I use
YouTube. And I blindly followed it.
So please ignore this.
Again sorry for wasting your important time.

**Comment by sahil431** [comment]
And currently I am doing this for hacktober fest!

**Pull request closed without merging**
