### PR TITLE
Added a document that demonstrates the performance benefits of docvalues

### PR DESCRIPTION
**Pull request by CascadingRadium**
sort_facet.md displays which query configuration utilizes docvalues and, through a test scenario, illustrates the trade-off between the increase in index size and the performance advantage gained in return.

### CODE REVIEW

**Review by abhinavdangeti — CHANGES_REQUESTED** [review]
@CascadingRadium Many tables' syntax appears broken. You can view how your markdown renders here - https://github.com/blevesearch/bleve/blob/docValues/docs/sort_facet.md

**Comment by CascadingRadium** [comment]
sorry for that.
The markdown viewer on my computer displayed the content correctly, so I mistakenly pushed it. However, I have resolved the issue now. The two images are encoded in base64, and unfortunately, they are not displayed properly in the GitHub markdown renderer due to a known problem described in this issue: https://github.com/github/markup/issues/270. If you download the file, you will be able to view the images correctly in any markdown viewer, such as MacDown on macOS.

**Comment by abhinavdangeti** [comment]
Can you confirm that the renderer is only failing on this pull request but once we merge github should be able to view content properly?

**Comment by CascadingRadium** [comment]
no; github itself does not allow rendering base64-encoded images, whether they are in a PR or are merged. If you clone the repo and view the file in any markdown renderer such as vscode, online, macdown it will show the image properly. this applies only to the two png images of the graphs, all the tables themselves are shown correctly

**Comment by CascadingRadium** [comment]
image in github
image

after cloning
image

**Comment by CascadingRadium** [comment]
Done

**Review by abhinavdangeti — APPROVED** [review]

**Pull request merged**
