### PR TITLE
scorch: fix crashes on ARM due to mis-aligned atomic access

### LINKED ISSUE #1231: scorch panics on arm (raspberry pi)
## uname -a
`
Linux raspberrypi 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux
`

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x12724]

goroutine 1 [running]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).openBolt(0x2af8000, 0xe0f1b8, 0x2af8000)
        /Users/darren/Sources/go/pkg/mod/github.com/blevesearch/bleve@v0.7.1-0.20190510153952-e0de6a8c9c5f/index/scorch/scorch.go:218 +0x12c
github.com/blevesearch/bleve/index/scorch.(*Scorch).Open(0x2af8000, 0x6, 0x280ac80)
        /Users/darren/Sources/go/pkg/mod/github.com/blevesearch/bleve@v0.7.1-0.20190510153952-e0de6a8c9c5f/index/scorch/scorch.go:160 +0x1c
github.com/blevesearch/bleve.openIndexUsing(0x28285a0, 0xb, 0x0, 0x2aba7d0, 0x0, 0x0)
        /Users/darren/Sources/go/pkg/mod/github.com/blevesearch/bleve@v0.7.1-0.20190510153952-e0de6a8c9c5f/index_impl.go:173 +0x434
github.com/blevesearch/bleve.Open(...)
        /Users/darren/Sources/go/pkg/mod/github.com/blevesearch/bleve@v0.7.1-0.20190510153952-e0de6a8c9c5f/index.go:286
```

Due to  https://github.com/golang/go/issues/599

### PR DESCRIPTION
**Pull request by tmm1**
opening on behalf of @darren

makes Scorch and cachedDocs aligned so that scorch run properly on arm

see the bottom of page on https://golang.org/pkg/sync/atomic/#pkg-note-BUG

fixes #1231

### CODE REVIEW

**Comment by tmm1** [comment]
@darren Could you please visit http://review.couchbase.org/#/settings/agreements and sign the CLA?

**Comment by darren** [comment]
@tmm1 
Thanks for open PR for me.

Yet I have problems with  signing the CLA, I entered AGREE and clicked but no warnings or errors.

screenshot

**Comment by tmm1** [comment]
You must type "I AGREE" not only "AGREE"

**Comment by darren** [comment]
@tmm1 
Thanks, Now I've siged the CLA.

**Comment by mschoch** [comment]
Can you verify @abhinavdangeti?

**Pull request merged**
