### PR TITLE
Added getters to boost and field query interfaces

### PR DESCRIPTION
**Pull request by slavikm**
It's really helpful to retrieve back the field and boost for our own query parser

### CODE REVIEW

**Comment by mschoch** [comment]
Can you explain how/why you use them?

We removed them because they clutter the code and were not actually used anywhere.

**Comment by slavikm** [comment]
So, we have our own query parser that also supports joins between indexes, etc. and when we pass in a query to the join function we might change it to another query and we need to get the field and boost values and translate them

**Comment by mschoch** [comment]
OK, well even if we decide to bring these back (which isn't decided yet).  We won't be able to use this commit.  Go convention is to not name getters GetXXX() but instead just use XXX().  Unfortunately, that means interface methods and struct members often collide for such fields.  So we'd have to go back and also rename the field members for Boost and Field.  The decision has already been made that these should be exported and not require the use of the interface, thus we end up with the ugly BoostVal, and FieldVal members coming back.  I'm really not excited about that.

**Comment by slavikm** [comment]
@mschoch what do you think? It will be helpful for us for a small cost of a bit of ugliness in the variable names

**Comment by mschoch** [comment]
I need more time to review this, think about your use case, and get other opinions.

We took a long time to introduce this change in the first place, asked for, but didn't get feedback and ended up here.  So, I don't think we should rush into undoing this either.

**Comment by aviadl** [comment]
@mschoch any news on this one ?
If not, when do you expect to have news ?
Thanks

**Comment by mschoch** [comment]
@aviadl  I had a coworker review it independently yesterday.  But no new options were presented.

@slavikm can you point me to one or more locations in your query parser where you need to access the field/boost?  I'd like to better understand the flow, where things are interfaces and where things are concrete structures.

**Comment by slavikm** [comment]
See below the code we use to handle joins between indexes. In many places we go through the interface and check the field / boost.

```go
package search

import (
	"strconv"
	"strings"

	"github.com/Sirupsen/logrus"
	"github.com/blevesearch/bleve"
	"github.com/demisto/server/errors"
)

const (
	// MainPrefix if no need to do joins
	MainPrefix = "main"
)

// JoinFunc returns a query to filter based on the IDs from the join
type JoinFunc func(ids []string) bleve.Query

// DocIDJoinFunc should be used when index is joined by it's natural ID
func DocIDJoinFunc(ids []string) bleve.Query {
	return bleve.NewDocIDQuery(ids)
}

// FieldJoinFunc should be used when the join is based on field name
func FieldJoinFunc(field string) JoinFunc {
	return func(ids []string) bleve.Query {
		q := bleve.NewDisjunctionQuery([]bleve.Query{})
		for _, id := range ids {
			termQuery := bleve.NewTermQuery(id).SetField(field)
			q.AddQuery(termQuery)
		}
		return q
	}
}

// FieldMapping holds for each index what function to run for the join
type FieldMapping struct {
	Join  JoinFunc // This is the function to return the query given the list of IDs
	Field string   // The field name in the index to query to get the IDs - can be empty to get the ID of the entity
}

// JoinInfo holds a list of indexes and their join mapping
type JoinInfo map[string]map[string]FieldMapping

// TranslateField to a different field with a query. For example, playbook is translated to playbookId field and list of IDs
type TranslateField struct {
	FieldName      string      // The field we should match on
	QueryFieldName string      // The field name in the translate query
	FieldNewName   string      // The new name of the field (real name in index)
	Index          bleve.Index // The index to run translate query on
}

// TranslateInfo holds a list of translates
type TranslateInfo []TranslateField

// parseFn represents the state of the parser as a function that returns the next state.
type parseFn func(*parser) parseFn

// queryType specifies the node type for each node in the tree
type queryType int

const (
	queryTypeNone   queryType = iota // empty node
	queryTypeSimple                  // simple node like match, range or phrase
	queryTypeBool                    // bool node with must,should and not
	queryTypeCon                     // AND node
	queryTypeDis                     // OR node
)

// node holds a node in the tree. The leafs are actual queries while the nodes are logical ops
type node struct {
	typ    queryType
	must   []bleve.Query
	should []bleve.Query
	not    []bleve.Query
	parent *node
	left   *node
	right  *node
}

// findEmpty node in the tree (type queryTypeNone)
func (n *node) findEmpty() *node {
	if n.left != nil {
		if empty := n.left.findEmpty(); empty != nil {
			return empty
		}
	}
	if n.typ == queryTypeNone {
		return n
	}
	if n.right != nil {
		return n.right.findEmpty()
	}
	return nil
}

// findLast leaf node (rightest)
func (n *node) findLast() *node {
	if n.right != nil {
		if last := n.right.findLast(); last != nil {
			return last
		}
	}
	if n.typ != queryTypeCon && n.typ != queryTypeDis {
		return n
	}
	if n.left != nil {
		return n.left.findLast()
	}
	return nil
}

// compile the node to a Bleve query
func (n *node) compile() bleve.Query {
	switch n.typ {
	case queryTypeSimple:
		logrus.Debug("Simple Query")
		return n.should[0] // fail if we have something weird
	case queryTypeNone:
		logrus.Debug("Nothing")
		return nil
	case queryTypeBool:
		logrus.Debugf("Bool - %+v", n)
		return bleve.NewBooleanQuery(n.must, n.should, n.not)
	case queryTypeCon, queryTypeDis:
		logrus.Debugf("Logical - %+v", n)
		var left, right bleve.Query
		if n.left != nil {
			left = n.left.compile()
		}
		if n.right != nil {
			right = n.right.compile()
		}
		if left != nil && right != nil {
			if n.typ == queryTypeCon {
				return bleve.NewConjunctionQuery([]bleve.Query{left, right})
			}
			return bleve.NewDisjunctionQuery([]bleve.Query{left, right})
		}
		return left
	}
	return nil
}

// parser holds the state of the parse process
type parser struct {
	indices       map[string]bleve.Index // the indexes we are going to use
	joinInfo      JoinInfo               // the join information for the given indexes
	translateInfo TranslateInfo          // the translate transformations we need to do on terms and phrases
	index         string                 // the current index we are using
	state         parseFn                // the next parse function to enter
	pos           int                    // current token input
	tokens        []item                 // the tokens the lexer returned
	root          *node                  // the current parsed tree
	currField     string                 // the current field part of query
	currMust      string                 // the current must or not part of query
}

// next returns the next token and moves forward
func (p *parser) next() *item {
	if p.pos >= len(p.tokens) {
		return nil
	}
	token := &p.tokens[p.pos]
	p.pos++
	return token
}

// prev returns the previous token without changing position
func (p *parser) prev() *item {
	if p.pos == 0 {
		return nil
	}
	return &p.tokens[p.pos-1]
}

// peek returns but does not consume the next token
func (p *parser) peek() *item {
	t := p.next()
	if t != nil {
		p.backup()
	}
	return t
}

// backup steps back one token
func (p *parser) backup() {
	p.pos--
}

// reset the parser for the particular index
func (p *parser) reset(index string) {
	p.index = index
	p.state = parseStart
	p.pos = 0
	p.root = &node{typ: queryTypeNone}
	p.currField = ""
	p.currMust = ""
}

// parse creates the parser instance with the indices and the lexer by collecting
// all tokens from the lexer
func parse(l *lexer, indices map[string]bleve.Index, joinInfo JoinInfo, translateInfo TranslateInfo) (*parser, error) {
	p := &parser{indices: indices, joinInfo: joinInfo, translateInfo: translateInfo}
	for {
		item := l.nextItem()
		switch item.typ {
		case itemError:
			return nil, errors.NewErrorf(errors.SearchIrlErr, "Error %s near position %d", item.val, item.pos)
		case itemEOF:
			return p, nil
		default:
			p.tokens = append(p.tokens, item)
		}
	}
}

// Parse the input query and return the Bleve querys (for each index) to be executed
func Parse(q string, indices map[string]bleve.Index, joinInfo JoinInfo, translateInfo TranslateInfo) (map[string]bleve.Query, error) {
	l := lex(q)
	p, err := parse(l, indices, joinInfo, translateInfo)
	if err != nil {
		return nil, err
	}
	queries := make(map[string]bleve.Query)
	// No need for joins, just do simple query parsing
	queryIndexes := []string{MainPrefix}
	if indices != nil && joinInfo != nil {
		queryIndexes = []string{}
		for k := range indices {
			queryIndexes = append(queryIndexes, k)
		}
	}
	for _, index := range queryIndexes {
		p.reset(index)
		for p.state = parseStart; p.state != nil; {
			p.state = p.state(p)
		}
		// Just in case we had lparen without closing rparen
		for p.root.parent != nil {
			q := p.root.compile()
			p.root = p.root.parent
			addToTree(p, q)
		}
		queries[index] = p.root.compile()
	}
	return queries, nil
}

// parseStart state in between query parts
func parseStart(p *parser) parseFn {
	token := p.peek()
	if token == nil {
		return nil
	}
	switch token.typ {
	case itemMustMustNot:
		p.currMust = token.val
		p.currField = ""
	case itemTerm:
		return parseTerm
	case itemPhrase:
		return parsePhrase
	case itemField:
		return parseField
	case itemAnd:
		p.currMust = ""
		p.currField = ""
		return parseAnd
	case itemOr:
		p.currMust = ""
		p.currField = ""
		return parseOr
	case itemLParen:
		p.currMust = ""
		p.currField = ""
		return parseLParen
	case itemRParen:
		p.currMust = ""
		p.currField = ""
		return parseRParen
	default:
		p.currMust = ""
		p.currField = ""
	}
	p.next()
	return parseStart
}

// handleBoost token and consume it
func handleBoost(p *parser, q bleve.Query, i *item) {
	b, err := strconv.ParseFloat(i.val, 64)
	if err == nil {
		q.SetBoost(b)
	}
	p.next()
}

// addToTree the current query
func addToTree(p *parser, q bleve.Query) {
	curr := p.root.findEmpty()
	if curr == nil {
		curr = p.root.findLast()
	}
	// This should neveer happen, something really messed up with query
	if curr == nil {
		curr = &node{typ: queryTypeNone}
		p.root = curr
	}
	if p.currMust != "" {
		curr.typ = queryTypeBool
		if p.currMust == "+" {
			curr.must = append(curr.must, q)
		} else {
			curr.not = append(curr.not, q)
		}
	} else {
		if curr.typ == queryTypeNone {
			curr.typ = queryTypeSimple
		} else {
			curr.typ = queryTypeBool
		}
		curr.should = append(curr.should, q)
	}
	p.currField = ""
	p.currMust = ""
}

// handleCrossIndexFields replaces queries when required for the current index
func handleCrossIndexFields(p *parser, q bleve.Query) bleve.Query {
	// If we do not need to do joins, just return original query
	if p.indices == nil || p.joinInfo == nil {
		return handleTranslate(p, q)
	}
	field := strings.ToLower(p.currField)
	// Iterate on the join information
	for indexName, actualIndex := range p.indices {
		// If field is the form of index:term or index.field:term
		if field == indexName || strings.HasPrefix(field, indexName+".") {
			logrus.Debugf("Encountered prefix %s", indexName)
			// Strip the index for the query field
			if field == indexName {
				q.SetField("")
			} else {
				q.SetField(q.Field()[len(indexName)+1:])
				logrus.Debugf("Field is %s", q.Field())
			}
			if p.index == indexName {
				logrus.Debugf("Running on the same index - %s, returning query unchanged", indexName)
				return handleTranslate(p, q)
			}
			if joinInfo, ok := p.joinInfo[p.index]; ok {
				if mapping, ok1 := joinInfo[indexName]; ok1 {
					logrus.Debugf("Doing join on %s by querying %s and retrieving field [%s]", p.index, indexName, mapping.Field)
					sr := bleve.NewSearchRequestOptions(handleTranslate(p, q), 10000, 0, false)
					// Sometimes we need only the ID
					if mapping.Field != "" {
						sr.Fields = []string{mapping.Field}
					}
					res, err := actualIndex.Search(sr)
					if err != nil {
						logrus.Infof("Error in join %v", err)
						return q
					}
					uniqueIDs := make(map[string]bool)
					for i := range res.Hits {
						if mapping.Field != "" {
							switch t := res.Hits[i].Fields[mapping.Field].(type) {
							case string:
								uniqueIDs[t] = true
							case []*string:
								for j := range t {
									uniqueIDs[*t[j]] = true
								}
							default:
								logrus.Errorf("Unsupported field type with version: %+v", t)
								uniqueIDs["-1"] = true
							}
						} else {
							uniqueIDs[res.Hits[i].ID] = true
						}
					}
					var ids []string
					for k := range uniqueIDs {
						ids = append(ids, k)
					}
					replaceQuery := mapping.Join(ids)
					if replaceQuery == nil {
						return nil
					}
					replaceQuery.SetBoost(q.Boost())
					return replaceQuery
				}
			}
			break
		}
	}
	return handleTranslate(p, q)
}

// handleTranslate of a given query to a different query based on translation info
func handleTranslate(p *parser, q bleve.Query) bleve.Query {
	field := strings.ToLower(q.Field())
	for i := range p.translateInfo {
		tField := p.translateInfo[i].FieldName
		if field == tField || strings.HasSuffix(field, "."+tField) {
			q.SetField(p.translateInfo[i].QueryFieldName)
			sr := bleve.NewSearchRequestOptions(q, 10000, 0, false)
			res, err := p.translateInfo[i].Index.Search(sr)
			if err != nil {
				logrus.Infof("Error in translate %v", err)
				return q
			}
			uniqueIDs := make(map[string]bool)
			for i := range res.Hits {
				uniqueIDs[res.Hits[i].ID] = true
			}
			var ids []string
			for k := range uniqueIDs {
				ids = append(ids, k)
			}
			newFieldName := p.translateInfo[i].FieldNewName
			if newFieldName == "" {
				newFieldName = field
			}
			return FieldJoinFunc(newFieldName)(ids)
		}
	}
	return q
}

// parseTerm and consume it while handing boost and fuzzy
func parseTerm(p *parser) parseFn {
	term := p.next()
	next := p.peek()
	var q bleve.Query
	termQ := bleve.NewMatchQuery(term.val)
	q = termQ
	if strings.Contains(term.val, "*") {
		q = bleve.NewWildcardQuery(term.val)
	} else if term.val == "F" || term.val == "T" || term.val == "f" || term.val == "t" {
		v := term.val == "T" || term.val == "t"
		q = bleve.NewBoolFieldQuery(v)
	}
	q.SetField(p.currField)
	if next != nil {
		switch next.typ {
		case itemBoost:
			handleBoost(p, q, next)
		case itemFuzzy:
			f, err := strconv.ParseInt(next.val, 10, 0)
			if err == nil {
				termQ.SetFuzziness(int(f))
			}
			p.next()
			next = p.peek()
			if next.typ == itemBoost {
				handleBoost(p, q, next)
			}
		}
	}
	addToTree(p, handleCrossIndexFields(p, q))
	return parseStart
}

// parsePhrase and consume it while handing boost (fuzzy is not supported by Bleve)
func parsePhrase(p *parser) parseFn {
	term := p.next()
	next := p.peek()
	q := bleve.NewMatchPhraseQuery(term.val)
	q.SetField(p.currField)
	if next != nil {
		switch next.typ {
		case itemBoost:
			handleBoost(p, q, next)
		case itemFuzzy:
			// Ignore, currently not supported by Bleve
			p.next()
			next = p.peek()
			if next.typ == itemBoost {
				handleBoost(p, q, next)
			}
		}
	}
	addToTree(p, handleCrossIndexFields(p, q))
	return parseStart
}

// parseField and consume it.
// Either handle range operators or just set the field on the parser
func parseField(p *parser) parseFn {
	token := p.next()
	p.currField = token.val
	next := p.next()
	num := p.peek()
	// If we have a field without value, just treat as term
	if next == nil {
		p.currField = ""
		p.backup()
		return parseTerm
	}
	// This is not a range but regular term or phrase
	if next == nil || num == nil ||
		next.typ != itemOpGreater && next.typ != itemOpGreaterEq && next.typ != itemOpLess && next.typ != itemOpLessEq && next.typ != itemOpEq ||
		num.typ != itemNumber && num.typ != itemDate && num.typ != itemDateTime {
		p.backup()
		return parseStart
	}
	var q bleve.Query
	if num.typ == itemNumber {
		val, err := strconv.ParseFloat(num.val, 64)
		if err != nil {
			p.backup()
			return parseStart
		}
		p.next() // consume the number as well
		switch next.typ {
		case itemOpGreater:
			inc := false
			q = bleve.NewNumericRangeInclusiveQuery(&val, nil, &inc, nil)
		case itemOpGreaterEq:
			inc := true
			q = bleve.NewNumericRangeInclusiveQuery(&val, nil, &inc, nil)
		case itemOpLess:
			inc := false
			q = bleve.NewNumericRangeInclusiveQuery(nil, &val, nil, &inc)
		case itemOpLessEq:
			inc := true
			q = bleve.NewNumericRangeInclusiveQuery(nil, &val, nil, &inc)
		case itemOpEq:
			inc := true
			q = bleve.NewNumericRangeInclusiveQuery(&val, &val, &inc, &inc)
		}
	} else {
		p.next() // consume the date as well
		switch next.typ {
		case itemOpGreater:
			inc := false
			q = bleve.NewDateRangeInclusiveQuery(&num.val, nil, &inc, nil)
		case itemOpGreaterEq:
			inc := true
			q = bleve.NewDateRangeInclusiveQuery(&num.val, nil, &inc, nil)
		case itemOpLess:
			inc := false
			q = bleve.NewDateRangeInclusiveQuery(nil, &num.val, nil, &inc)
		case itemOpLessEq:
			inc := true
			q = bleve.NewDateRangeInclusiveQuery(nil, &num.val, nil, &inc)
		case itemOpEq:
			inc := true
			q = bleve.NewDateRangeInclusiveQuery(&num.val, &num.val, &inc, &inc)
		}
	}
	q.SetField(p.currField)
	boost := p.peek()
	if boost != nil && boost.typ == itemBoost {
		handleBoost(p, q, boost)
	}
	addToTree(p, handleCrossIndexFields(p, q))
	return parseStart
}

// parseAnd by replacing the last (rightest) leaf (query) with an AND node
// and placing an empty node as the right child
func parseAnd(p *parser) parseFn {
	p.next()                                       // consume the AND
	if empty := p.root.findEmpty(); empty != nil { // in middle of another bool op, or empty, ignore
		return parseStart
	}
	curr := p.root.findLast()
	// Should never happen
	if curr == nil {
		return parseStart
	}
	left := &node{
		typ:    curr.typ,
		must:   curr.must,
		should: curr.should,
		not:    curr.not,
		parent: curr,
	}
	right := &node{
		typ:    queryTypeNone,
		parent: curr,
	}
	curr.typ = queryTypeCon
	curr.must, curr.should, curr.not = nil, nil, nil
	curr.left, curr.right = left, right
	return parseStart
}

// parseOr by replacing the root with the or and original root as left child
func parseOr(p *parser) parseFn {
	p.next()                                       // consume the OR
	if empty := p.root.findEmpty(); empty != nil { // in middle of another bool op, or empty, ignore
		return parseStart
	}
	root := &node{
		typ:    queryTypeDis,
		parent: p.root.parent,
		left:   p.root,
	}
	right := &node{
		typ:    queryTypeNone,
		parent: root,
	}
	root.right = right
	p.root = root
	return parseStart
}

// parseLParen by temporary (until rparen) replacing the root
func parseLParen(p *parser) parseFn {
	p.next() // consume it
	root := &node{typ: queryTypeNone, parent: p.root}
	p.root = root
	return parseStart
}

// parseRParen by poping the original root and placing the compiled query in the right place
func parseRParen(p *parser) parseFn {
	p.next() // consume it
	oldRoot := p.root.parent
	if oldRoot == nil {
		return parseStart // ignore
	}
	q := p.root.compile()
	p.root = oldRoot
	addToTree(p, q)
	return parseStart
}
```

**Comment by mschoch** [comment]
OK, so I'm coming around to being OK with this change.

One question, I don't see `boolean.go` in the changeset, but that type of Query is also Boostable.  Are there any others missing?

**Comment by slavikm** [comment]
@mschoch I believe it now captures all Boostable and is ready

**Comment by aviadl** [comment]
@mschoch Is there any thing specific that prevents the merge of this one ?

**Comment by mschoch** [comment]
i'm in the process of testing now, should be merged today

**Pull request merged**
