### PR TITLE
Allow bulk command to specify document id instead of using a random id

### PR DESCRIPTION
**Pull request by blamoo**
This change allows me to specify the document id as a string before each line, like this:

Bulk file:
```json
"doc1"
{"name": "Chico Anysio"}
"doc2"
{"name": "Jô Soares"}
"doc3"
{"name": "Paulo Silvino"}
"doc4"
{"name": "Agildo Ribeiro"}
"doc5"
{"name": "José Vasconcellos"}
```

Output:
```
PS D:\Users\Blamoo\Projects\bleve> bleve bulk ../brazilian-comedians.index ../brazilian-comedians.ndjson
Indexing: ../brazilian-comedians.ndjson
Indexing batch (0 docs)...

PS D:\Users\Blamoo\Projects\bleve> bleve query ../brazilian-comedians.index name:*
5 matches, showing 1 through 5, took 998.4µs
    1. doc1 (0.171398)
        name
                Chico Anysio
    2. doc4 (0.171398)
        name
                Agildo Ribeiro
    3. doc3 (0.171398)
        name
                Paulo Silvino
    4. doc5 (0.171398)
        name
                José Vasconcellos
    5. doc2 (0.171398)
        name
                Jô Soares
```

### CODE REVIEW

**Comment by mschoch** [comment]
As of v2.0.0 the  bulk command is deprecated: https://github.com/blevesearch/bleve/issues/1495

As we plan to remove this in a future release, I do think we have any plans to update the functionality.  We recommend users implement this type of logic in their own application.

**Comment by blamoo** [comment]
I see this command more like a prototyping/learning tool than a production-ready tool... But I don't get what you mean by saying it's "extremely limited because they assume and only work with the default index mapping" in the v2 proposal.

These sub-commands allow me to both create complex indexes by passing a complex JSON mapping and index complex JSON documents... Isn't that enough to access most of Bleve's complex features? I mean, it's exactly the same structure used in a lot of tests.

**Comment by mschoch** [comment]
> But I don't get what you mean by saying it's "extremely limited because they assume and only work with the default index mapping" in the v2 proposal.

I think I misspoke here, as you are right, that is not correct.  The `bleve create` command allows you to provide a custom mapping JSON file.  Instead, what I would say is that the limitation is that the mappings you can use are limited to what was compiled in at the time you build the bleve command.  Now, one might say, that's ok, that's a reasonable limiation for prototyping/learning.  But the problem is that we've been working to remove unnecessary dependencies in the project, and the bleve tool is problematic in this area.  Today it uses a long list of forced imports to include a variety of functionality out of the box.

> These sub-commands allow me to both create complex indexes by passing a complex JSON mapping and index complex JSON documents... Isn't that enough to access most of Bleve's complex features?

The problem is that this is highly subjective.  It gives preference to languages that we can easily support without external dependencies, and excludes languages which need them.

To me the decision to remove these commands is clear because in practice I can never actually use these commands when I wan to.  For example, when a user encounters some problem, and they share their index with me, can i run `bleve search` to test it out? No, instead I get an error message that the analyzer named "XYZ" cannot be found.  Because in practice, everyone uses custom analyzers.

I also think that this PR shows why keeping these tools around just for prototyping/learning is problematic.  We have received many PRs like this one that seek to support some new file format, or some new representation of the data.  In the end, there is no standard format that will satisfy everyone, and we have no interest in building out this tool to support all such use cases.  Our belief is that it's much easier for users to build their own 100-line program to do exactly what they want.

> I mean, it's exactly the same structure used in a lot of tests.

I don't follow what this has to do with keep/removing/enhancing the bleve command-line tooling.

**Comment by blamoo** [comment]
> But the problem is that we've been working to remove unnecessary dependencies in the project, and the bleve tool is problematic in this area. Today it uses a long list of forced imports to include a variety of functionality out of the box.

Thinking that way, in my opinion it might even make more sense to remove the CLI tool completely from the main code and move it to a separate project.

Well, in such scenario, this PR does not make sense at all. Thank you anyways.

**Pull request closed without merging**
