### PR TITLE
Fix token start/end/position values in camelCase tokenizer

### LINKED ISSUE #613: camelCase TokenFilter zeros out Start/End/Position
The tokens in the `TokenStream` returned by `CamelCaseFilter.Filter(..)` have zero Start/End/Position values, regardless of the Start/End/Position values of the input tokens.

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fixes #613.

### CODE REVIEW

**Comment by mschoch** [comment]
Pinging @a-little-srdjan for review, since this was code he contributed.

**Comment by a-little-srdjan** [comment]
Yes, this looks good to me.

**Comment by a-little-srdjan** [comment]
Sorry for such a late reply. I am kinda breaking into pieces at my company :(

**Comment by mschoch** [comment]
Oops, I merged before checking.  Can you please sign the CLA as described here:

https://github.com/blevesearch/bleve/blob/master/CONTRIBUTING.md

**Comment by ethantkoenig** [comment]
@mschoch Signed

**Comment by mschoch** [comment]
Thanks.

**Pull request merged**
